version: '2'
catalog:
  name: InfluxDB
  description: Timeout series database
  version: v0.10
  questions:
    - variable: TRAEFIK_DOMAIN
      description: Base domain name
      label: Domain Name
      type: string
      required: true
      default: kronkltd.net
services:
  influxdb:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8086
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
