version: '2'
catalog:
  name: MySQL
  version: v0.1.0
  description: |
    MySQL Instance
  questions:
    - variable: rootPassword
      label: Root Password
      description: |
        default: "perfectloops"
      default: "perfectloops"
      required: true
      type: password
services:
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 3306
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
