name: Jiksnu
description: |
  Distributed Social Networking
version: v0.3.0
category: Blogging
maintainer: Daniel E. Renfer <duck@kronkltd.net>
license: gpl-3.0
projectURL: https://github.com/kronkltd/jiksnu
