version: '2'
services:
  node-exporter:
    image: prom/node-exporter:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
  prom-conf:
    image: infinityworks/prom-conf:17
    network_mode: none
    volumes:
      - conf:/etc/prom-conf/
    tty: true
    links:
      - node-exporter:node-exporter
      - prometheus-rancher-exporter:prometheus-rancher-exporter
      - cadvisor:cadvisor
  cadvisor:
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
  prometheus-rancher-exporter:
    image: infinityworks/prometheus-rancher-exporter:v0.22.40
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  prometheus:
    image: prom/prometheus:v1.4.1
    tty: true
    links:
      - node-exporter:node-exporter
      - prometheus-rancher-exporter:prometheus-rancher-exporter
      - cadvisor:cadvisor
    volumes:
      - conf:/etc/prom-conf
      - data:/prometheus
    command:
      - -alertmanager.url=http://alertmanager:9093
      - -config.file=/etc/prom-conf/prometheus.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles
    labels:
      io.rancher.sidekicks: prom-conf
      traefik.port: "9090"
      traefik.enable: stack
      traefik.domain: ${TRAEFIK_DOMAIN}
volumes:
  conf:
    driver: local
  data:
    driver: local
