version: '2'
catalog:
  name: Prometheus
  description: Metrics Collection
  version: v1.4.1
  questions:
    - variable: INFLUXDB_LINK
      label: InfluxDB service
      type: service
      required: true
      default: influxdb/influxdb
      description: InfluxDB service link
    - variable: TRAEFIK_DOMAIN
      description: Base domain name
      label: Domain Name
      type: string
      required: true
      default: kronkltd.net
    - variable: VOLUME_DRIVER
      description: Volume Driver
      label: Volume Driver
      type: string
      required: true
      default: local
services:
  node-exporter:
    start_on_create: true
  prom-conf:
    scale: 1
    start_on_create: true
  cadvisor:
    start_on_create: true
  prometheus-rancher-exporter:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 9173
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
  prometheus:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 9090
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
