sentry:
  image: slafs/sentry
  links:
    - postgresdb
    - redis
    - sentry_worker
  environment:
    VIRTUAL_HOST: "sentry.docker"
  volumes:
    - /data

sentry_worker:
  image: slafs/sentry
  command: celery worker -B
  links:
    - postgresdb
    - redis
  environment:
    C_FORCE_ROOT: "true"
  volumes:
    - /data

redis:
  image: redis:3

postgresdb:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql/data
