sentry:
  image: slafs/sentry
  depends_on:
    - postgresdb
    - redis
    - sentry_worker
    - proxy
  env_file: docker/sentry/environment
  environment:
    VIRTUAL_HOST: "sentry.docker"
  volumes:
    - sentry-files:/data

sentry_worker:
  image: slafs/sentry
  command: celery worker -B
  depends_on:
    - postgresdb
    - redis
  env_file: docker/sentry/environment
  environment:
    C_FORCE_ROOT: "true"
  volumes:
    - sentry-files:/data
