version: '2'
services:
  traefik-conf:
    image: rawmind/rancher-traefik:0.3.4-14
    network_mode: none
    volumes:
    - /opt/tools
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.global: 'true'
  traefik:
    image: rawmind/alpine-traefik:1.1.2
    environment:
      CONF_INTERVAL: '10'
      TRAEFIK_ACME_EMAIL: duck@kronkltd.net
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_ONDEMAND: 'true'
      TRAEFIK_ACME_ONHOSTRULE: 'true'
      TRAEFIK_HTTPS_ENABLE: only
      TRAEFIK_HTTPS_PORT: '443'
      TRAEFIK_HTTP_PORT: '80'
    tty: true
    volumes_from:
    - traefik-conf
    ports:
    - 8000:8000/tcp
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.sidekicks: traefik-conf
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.global: 'true'
  dashboard:
    image: duck1123/docker-nginx-basic-auth
    environment:
      FORWARD_PORT: '8000'
    stdin_open: true
    tty: true
    links:
    - traefik:web
    labels:
      traefik.port: '80'
      traefik.enable: stack
      traefik.domain: kronkltd.net
      io.rancher.container.pull_image: always
