JiksnuLB:
  ports:
    - 8082:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - jiksnu
  stdin_open: true

jiksnu:
  image: repo.jiksnu.org/duck1123/jiksnu
  environment:
    DOMAIN: jiksnu.com
  links:
    - mongo

mongo:
  image: mongo
