version: '2'
catalog:
  name: "Jiksnu"
  version: 0.3.0
  description: "Distributed Social Network"
  questions:
    - variable: DOMAIN
      label: Site Domain
      required: true
      description: |
        Domain
      type: string
    - variable: SENTRY_DSN
      label: Sentry DSN
      description: |
        The DSN for a sentry server to receive error reports
      type: string
    - variable: TRAEFIK_DOMAIN
      label: Traefik Domain
      description: |
        Base URL of host
      type: string
services:
  jiksnu:
    scale: 1
    start_on_create: true
    health_check:
      port: 8080
      interval: 2000
      initializing_timeout: 60000000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 2000
      request_line: GET "/status" "HTTP/1.0"
      healthy_threshold: 2
  mongo:
    scale: 1
    start_on_create: true
