version: '2'
services:
  grafana:
    image: grafana/grafana:4.0.2
    tty: true
    external_links:
      - ${INFLUXDB_LINK}:influxdb
      - ${PROMETHEUS_LINK}:prometheus
      - ${PROMETHEUS_RANCHER_EXPORTER_LINK}:prometheus-rancher-exporter
    volumes:
      - data:/var/lib/grafana/
      - config:/etc/grafana/
      - logs:/var/log/grafana/
    labels:
      io.rancher.sidekicks: graf-db
      traefik.enable: stack
      traefik.port: '3000'
      traefik.domain: ${TRAEFIK_DOMAIN}
  graf-db:
    image: infinityworks/graf-db:10
    network_mode: none
    volumes:
      - data:/var/lib/grafana/
    tty: true
    external_links:
      - ${INFLUXDB_LINK}:influxdb
      - ${PROMETHEUS_LINK}:prometheus
      - ${PROMETHEUS_RANCHER_EXPORTER_LINK}:prometheus-rancher-exporter
    command:
      - cat
volumes:
  data:
    driver: ${VOLUME_DRIVER}
  config:
    driver: ${VOLUME_DRIVER}
  logs:
    driver: ${VOLUME_DRIVER}
